"use strict";
console.log("Hello from external JavaScript!");
    alert('Welcome to my Website!');
    var userAnswer= prompt("What is your favorite color?");
    alert("No way! " + userAnswer + " Is my favorite color too!");
    alert(" You wanted to rent, TheLittleMermaid, BrotherBear, and Hercules.");
    var littleMermaidDays= prompt('How many days for LittleMermaid?');
    var brotherBearDays= prompt('How many days for BrotherBear?');
    var herculesDays= prompt('How many days for Hercules?');
    var dailyRate= 3;
    alert(littleMermaidDays * dailyRate + "$ is the total for TheLittleMermaid");
    alert(brotherBearDays * dailyRate + "$ is the total for BrotherBear");
    alert(herculesDays * dailyRate + "$ is the total for Hercules");
    alert("Thank you for shopping at BlockBuster!");